# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN yarn install --production

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app /app

CMD ["node", "src/index.js"]
