# Build stage
FROM node:20.9.0-slim AS builder

WORKDIR /app

COPY . .

RUN yarn install --production

# Production stage
FROM node:20.9.0-slim

WORKDIR /app

COPY --from=builder /app /app
HEALTHCHECK --interval=5m --timeout=3s CMD curl --fail http://localhost:3000 || exit 1
CMD ["node", "src/index.js"]
